services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Открываем порт 80 для доступа к сайту
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - ./www:/usr/share/nginx/html:ro #
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Монтируем конфиг Nginx
    restart: always